### ISSUE TITLE
make -j error

### ISSUE THREAD

**Issue by Naima2002** [jeongminpark417/GIDS#10]
Hello,

I am running into this issue when I execute make -j
We have CUDA 12.3 on our system. I have also tried to make this work with other CUDA versions (12.1) but have been unsuccessful. BaM works fine (I tested it by running the example benchmarks). Would appreciate any help here.

make -j
[ 50%] Building CUDA object CMakeFiles/BAM_Feature_Store.dir/gids_nvme.cu.o
In file included from /home/bam/include/buffer.h:14,
                 from /home/bam/GIDS/gids_module/./include/bam_nvme.h:4,
                 from /home/bam/GIDS/gids_module/gids_nvme.cu:16:
/home/bam/include/nvm_types.h:10:10: fatal error: simt/atomic: No such file or directory
   10 | #include <simt/atomic>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/BAM_Feature_Store.dir/build.make:77: CMakeFiles/BAM_Feature_Store.dir/gids_nvme.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/BAM_Feature_Store.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by jeongminpark417** [comment]
This seems like you did not add submodules. Try `git submodule update --recursive `

**Comment by Naima2002** [comment]
That worked, thank you!
